/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulpgrupo61.vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import universidadulpgrupo61.accesoADatos.AlumnoData;
import universidadulpgrupo61.accesoADatos.InscripcionData;
import universidadulpgrupo61.accesoADatos.MateriaData;
import universidadulpgrupo61.entidades.*;

/**
 *
 * @author ferge
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    public FormularioInscripcion() {
        initComponents();
        this.setTitle("Formulario Inscripcion");
        cargarComboAlumnos();
        cargarTablaInscripciones();

        //PREGUNTAR ACTIONLISTENER
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        rbInscriptas = new javax.swing.JRadioButton();
        rbNoInscriptas = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInscripciones = new javax.swing.JTable();
        btnIncribir = new javax.swing.JButton();
        btnAnularInscripcion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboAlumno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 427, 10));

        jPanel2.setBackground(new java.awt.Color(148, 56, 95));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbInscriptas.setContentAreaFilled(false);
        rbInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInscriptasActionPerformed(evt);
            }
        });
        rbInscriptas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rbInscriptasPropertyChange(evt);
            }
        });
        jPanel2.add(rbInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        rbNoInscriptas.setContentAreaFilled(false);
        rbNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoInscriptasActionPerformed(evt);
            }
        });
        jPanel2.add(rbNoInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Materias Inscriptas");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Materias NO Inscriptas");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 200, -1));

        tbInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbInscripciones.setOpaque(false);
        jScrollPane1.setViewportView(tbInscripciones);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 510, 140));

        btnIncribir.setForeground(new java.awt.Color(0, 0, 0));
        btnIncribir.setText("Inscribir");
        btnIncribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncribirActionPerformed(evt);
            }
        });
        jPanel2.add(btnIncribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, -1));

        btnAnularInscripcion.setForeground(new java.awt.Color(0, 0, 0));
        btnAnularInscripcion.setText("Anular Inscripción");
        btnAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularInscripcionActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnularInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 140, -1));

        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 71, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Listado de Materias");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 530, 280));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione un alumno:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 230, -1));

        cboAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAlumnoItemStateChanged(evt);
            }
        });
        cboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAlumnoActionPerformed(evt);
            }
        });
        cboAlumno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboAlumnoPropertyChange(evt);
            }
        });
        jPanel1.add(cboAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 300, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Formulario de Inscripción");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIncribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncribirActionPerformed
        if (tbInscripciones.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una materia.");
            return;
        }

        InscripcionData iD = new InscripcionData();

        Alumno alum = (Alumno) cboAlumno.getSelectedItem();

        int idMat = (Integer) tbInscripciones.getValueAt(tbInscripciones.getSelectedRow(), 0);
        MateriaData mD = new MateriaData();
        Materia mat = mD.buscarMateria(idMat);

        Inscripcion insc = new Inscripcion(alum, mat);

        iD.guardarInscripcion(insc);
        this.rbNoInscriptasActionPerformed(null);
    }//GEN-LAST:event_btnIncribirActionPerformed

    private void btnAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularInscripcionActionPerformed
        if (tbInscripciones.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una materia.");
            return;
        }

        InscripcionData iD = new InscripcionData();

        Alumno alum = (Alumno) cboAlumno.getSelectedItem();

        int idMat = (Integer) tbInscripciones.getValueAt(tbInscripciones.getSelectedRow(), 0);

        int x = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar la inscripción?", "Eliminar", JOptionPane.YES_NO_OPTION);

        if (x == JOptionPane.YES_OPTION) {
            iD.borrarInscripcion(alum.getIdAlumno(), idMat);
        }
        this.rbInscriptasActionPerformed(null);
    }//GEN-LAST:event_btnAnularInscripcionActionPerformed

    private void rbInscriptasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rbInscriptasPropertyChange

    }//GEN-LAST:event_rbInscriptasPropertyChange


    private void rbInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInscriptasActionPerformed
        if (cboAlumno.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno.");
            rbInscriptas.setSelected(false);
            return;
        }

        rbInscriptas.setSelected(true);
        rbNoInscriptas.setSelected(false);
        btnAnularInscripcion.setEnabled(true);
        btnIncribir.setEnabled(false);

        mostrarDatosTabla();
    }//GEN-LAST:event_rbInscriptasActionPerformed

    private void rbNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoInscriptasActionPerformed

        if (cboAlumno.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno.");
            rbNoInscriptas.setSelected(false);
            return;
        }

        rbNoInscriptas.setSelected(true);
        rbInscriptas.setSelected(false);
        btnAnularInscripcion.setEnabled(false);
        btnIncribir.setEnabled(true);

        mostrarDatosTabla();

    }//GEN-LAST:event_rbNoInscriptasActionPerformed

    private void cboAlumnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboAlumnoPropertyChange

    }//GEN-LAST:event_cboAlumnoPropertyChange

    private void cboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAlumnoActionPerformed

    private void cboAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAlumnoItemStateChanged
        mostrarDatosTabla();
    }//GEN-LAST:event_cboAlumnoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularInscripcion;
    private javax.swing.JButton btnIncribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Alumno> cboAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbInscriptas;
    private javax.swing.JRadioButton rbNoInscriptas;
    private javax.swing.JTable tbInscripciones;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/asd.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

    private void cargarComboAlumnos() {
        AlumnoData aD = new AlumnoData();
        List<Alumno> alumnos = aD.listarAlumnos();

        cboAlumno.addItem(null);

        for (Alumno alumno : alumnos) {
            cboAlumno.addItem(alumno);
        }

    }

    private void cargarTablaInscripciones() {
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");

        tbInscripciones.setModel(modelo);

    }

    private void mostrarDatosTabla() {
        if(cboAlumno.getSelectedItem()==null){
            modelo.setRowCount(0);
            return;
        }
        InscripcionData iD = new InscripcionData();
        Alumno a = (Alumno) cboAlumno.getSelectedItem();

        List<Materia> materias = new ArrayList<>();
    
            if (rbNoInscriptas.isSelected()) {
                materias = iD.obtenerMateriasNoCursadas(a.getIdAlumno());
            } else if (rbInscriptas.isSelected()) {
                materias = iD.obtenerMateriasCursadas(a.getIdAlumno());
            }

            modelo.setRowCount(0);

            for (Materia materia : materias) {
                this.modelo.addRow(new Object[]{materia.getIdMateria(), materia.getNombre(), materia.getAnioMateria()});
            }
        }
    }

